required_directories:
  - src
  - output
required_files:
  - setup.cfg
  - pyproject.toml
  - lego_data_update.npz
  - Starry-Night-canvas-Vincent-van-Gogh-New-1889_12.jpg
optional_directories:
  - additional_data
optional_files:
  - README.txt